doc: add workaround to issue #44
dotdc/grafana-dashboards-kubernetes pull request #45
Opened 2023-04-28 18:18 UTC by Chewie

# Pull Request

## Required Fields

### :mag_right: What kind of change is it?

- docs

### :dart: What has been changed and why do we need it?

- Following the discussion on #44, this PR adds a workaround to relabel the output of the node-exporter. This fix works on the lab setup provided in the issue, but we still need to test it on other scenarios.

## Optional Fields

### :heavy_check_mark: Which issue(s) this PR fixes?

- #44

2023-05-02 07:10 UTC, dotdc requested changes

2023-05-02 07:10 UTC, dotdc commented on README.md
> +sourceLabels:
Replace with:
sourceLabels: [__meta_kubernetes_pod_node_name]

2023-05-02 07:10 UTC, dotdc commented on README.md
> +```yaml
Add:
```
# Example with kube-prometheus-stack values
prometheus-node-exporter:
  prometheus:
    monitor:
      relabelings:
```

2023-05-02 07:10 UTC, dotdc commented on README.md
> +
Add:

This syntax is for Prometheus Operator, for Prometheus:

`sourceLabels ` -> `source_labels`
`targetLabel ` -> `target_tabel`

2023-05-02 17:59 UTC, Chewie commented
Thank you for the feedback!

I was actually about to augment the PR after playing more with grafana agent. The agent actually has two modes : one is the operator, which uses servicemonitors and as such benefit from the same fix as prometheus operator, and one is the flow mode, with its own configuration language.

I've reworked the PR to incorporate both this info and your feedback.

2023-05-02 20:32 UTC, dotdc approved these changes

2023-05-02 20:35 UTC, merged

2023-05-02 20:39 UTC, dotdc commented
I think you covered the issue, thank you for your contribution!

2024-04-25 21:09 UTC, dotdc commented
:tada: This PR is included in version 1.1.0 :tada:

The release is available on [GitHub release](https://github.com/dotdc/grafana-dashboards-kubernetes/releases/tag/v1.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: