fix: match all non-idle cpu modes when calculating total cpu usage
dotdc/grafana-dashboards-kubernetes pull request #81
Opened 2023-12-18 13:09 UTC by uhthomas

Fixes: #80

# Pull Request

## Required Fields

### :mag_right: What kind of change is it?

- fix

### :dart: What has been changed and why do we need it?

- Total CPU usage is now calculated based on all non-idle CPU modes. This is needed to prevent reporting negative values.

## Optional Fields

### :heavy_check_mark: Which issue(s) this PR fixes?

- #80

### :speech_balloon: Additional information?

- ...

2023-12-20 12:41 UTC, jkroepke commented
I do my review here: https://github.com/dotdc/grafana-dashboards-kubernetes/issues/80#issuecomment-1864391306 

Unless I do something wrong, the values are more incorrect now.

2024-01-05 16:13 UTC, dotdc requested changes
Looks way better now!
Could you please remove the unneeded "sum by instance" on the nodes dashboard and bump the version on both dashboards (at the end)?

2024-01-05 16:13 UTC, dotdc commented on dashboards/k8s-views-nodes.json
> +          "expr": "avg(sum by (instance, cpu) (rate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\", instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval])))",
sum by cpu should be enough here.

2024-01-05 16:16 UTC, uhthomas commented
Done @dotdc

2024-01-05 16:20 UTC, merged

2024-01-05 16:24 UTC, uhthomas commented
> Thank you for your contribution @uhthomas ! 🎉

Thank you for your patience and help :) I'm glad we got there in the end.

2024-04-25 21:08 UTC, dotdc commented
:tada: This PR is included in version 1.1.0 :tada:

The release is available on [GitHub release](https://github.com/dotdc/grafana-dashboards-kubernetes/releases/tag/v1.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: