Re-Import Global, Namespace and Nodes
dotdc/grafana-dashboards-kubernetes pull request #98
Opened 2024-02-05 21:00 UTC by jkroepke

# Pull Request

## Required Fields

### :mag_right: What kind of change is it?

- chore

### :dart: What has been changed and why do we need it?

- Just an import and export of the dashboards json via export function.

## Optional Fields

### :heavy_check_mark: Which issue(s) this PR fixes?

- Fixes #97 

### :speech_balloon: Additional information?

- Reduces unnecessary diffs in a future PR

2024-02-06 11:51 UTC, jkroepke commented on dashboards/k8s-views-namespaces.json
> +      "name": "Time series",
No. I guess dependencies are just ordered now and in sort order, sort is before timeseries.

2024-02-06 11:52 UTC, jkroepke commented on dashboards/k8s-views-namespaces.json
> +  "id": null,
it was part of the export

2024-02-06 11:52 UTC, jkroepke commented on dashboards/k8s-views-global.json
> -  "__inputs": [
You are right, sometime goes wrong here

2024-02-06 12:14 UTC, dotdc commented on dashboards/k8s-views-namespaces.json
> +      "name": "Time series",
ok good to know :+1:

2024-02-10 21:29 UTC, jkroepke commented on dashboards/k8s-views-global.json
> +          "value": "d9803217-435f-4ee4-8d45-0e2f08370325"
```suggestion
          "text": "",
          "value": ""
```

2024-02-14 08:44 UTC, jkroepke commented
@dotdc did you had a chance for an additional review?

2024-02-14 08:57 UTC, dotdc commented
Hi @jkroepke,
Just had a look and there are still a few things to change, but I don't see any queries with Windows support.
Maybe it would be easier to make a dashboard, then review the dashboard api details on review?
It won't be a lot, and you already know how to fix most of it.
Let me know.

2024-02-14 09:06 UTC, jkroepke commented
> but I don't see any queries with Windows support.

This is correct. This PR should not contain any functional changes.

While I export the JSON dashboard with the windows changes first time, I had so many changes not related to Windows.

Base on that I decide to setup a PR that contains only changes from Grafana, if I do a import and export of the JSON again.

Windows related changed will be introduce in a follow PR

2024-02-14 09:10 UTC, dotdc requested changes

2024-02-14 09:10 UTC, dotdc commented on dashboards/k8s-views-global.json
> +  "version": 38,
+2 instead of +1

2024-02-14 09:10 UTC, dotdc commented on dashboards/k8s-views-global.json
> +  "id": null,
remove this line

2024-02-14 09:10 UTC, dotdc commented on dashboards/k8s-views-namespaces.json
> +  "id": null,
remove this line

2024-02-14 09:10 UTC, dotdc commented on dashboards/k8s-views-nodes.json
> +  "id": null,
remove this line

2024-02-14 09:13 UTC, dotdc commented
> > but I don't see any queries with Windows support.
> 
> This is correct. This PR should not contain any functional changes.
> 
> While I export the JSON dashboard with the windows changes first time, I had so many changes not related to Windows.
> 
> Base on that I decide to setup a PR that contains only changes from Grafana, if I do a import and export of the JSON again.
> 
> Windows related changed will be introduce in a follow PR

Sure, just made the review again. 
All the rest should be good.

When you'll make the real PR, I'll test the dashboards on my side, and we can fix issues (if any).

2024-02-14 09:34 UTC, jkroepke commented on dashboards/k8s-views-global.json
> +  "version": 38,
```suggestion
  "version": 37,
```

2024-02-14 09:34 UTC, jkroepke commented on dashboards/k8s-views-global.json
> +  "id": null,
```suggestion
```

2024-02-14 09:34 UTC, jkroepke commented on dashboards/k8s-views-namespaces.json
> +  "id": null,
```suggestion
```

2024-02-14 09:35 UTC, dotdc commented
@jkroepke 
Also, this is just a test, right? 
I don't think we'll be merging this without any functional changes.

2024-02-14 09:35 UTC, jkroepke commented
Changes applied as recommend.

2024-02-14 09:40 UTC, dotdc approved these changes

2024-02-14 09:42 UTC, dotdc commented
@jkroepke 
Do you want to merge this? Or was it just a test for the export?

2024-02-14 09:48 UTC, jkroepke commented
Yes, please merge, I will setup a second one.

2024-02-14 10:03 UTC, merged

2024-02-14 10:05 UTC, dotdc commented
@jkroepke 
Done, also pushed a commit with a version bump for the namespaces dashboard

2024-04-25 21:08 UTC, dotdc commented
:tada: This PR is included in version 1.1.0 :tada:

The release is available on [GitHub release](https://github.com/dotdc/grafana-dashboards-kubernetes/releases/tag/v1.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: